using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum QuestState: int
{
    NONE = 0,
    QUEST1_PHASE1_TALK_TO_EDNA,
    QUEST1_PHASE2_TALK_TO_BRYAN,
    QUEST1_PHASE3_GET_FD_FROM_FRANK,
    QUEST1_PHASE4_OPEN_DOCUMENT,
    QUEST2_PHASE1_TALK_TO_EDNA,
    QUEST2_PHASE2_TALK_TO_BRYAN,
    QUEST2_PHASE3_COMPLETE_WEBCHECKS,
    QUEST3_PHASE1_TALK_TO_BRYAN,
    QUEST3_PHASE2_COMPLETE_TASKS,
    QUEST_CLEAN_INFECTED,
}